# -*- coding: utf-8 -*-
"""Soroshi_Shinzam_Problem_Solved.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/davidproton4u/AI-sampleassng/blob/main/Soroshi_Shinzam_Problem_Solved.ipynb

PROBLEM ONE - NUMBER OF GRAINS IN A 100TH DAY
"""

#Problem One - Number of Grains
number_days = 100
total_grain_rice = 1

for i in range(1, number_days + 1):
    print(i, total_grain_rice) #This shows the amount of grains collected in a day
    total_grain_rice *=2

    #Grains of Rice in the 100th day would be represented below
    print("Sum of Rice in", i, "days is:", total_grain_rice)

number_days = 100
total_grain_rice = 1
#creating the values for the x and y axis
yaxis = []
xaxis = list(range(1, number_days + 1))

for i in range(1, number_days + 1,):
    #Listing the change in the rice grain
    print("for day: {} the total grain is: {}".format(i, total_grain_rice))

    #Appending the total grain rice into the list of the yaxis
    yaxis.append(total_grain_rice)
    total_grain_rice = 2**i
  
print("Sum of rice in", i, "days is: ", total_grain_rice)

"""Plotting the Graph for the Above"""

#Plotting the Graph to the Answer Above
import matplotlib.pyplot as plt

plt.xlabel('Number of Days Requested')
plt.ylabel('Number of Rice Grain')
plt.title('Change in the Number of Rice Grain')
plt.plot(xaxis, yaxis, linewidth=3.0)
plt.tick_params(labelsize=10)
plt.figure(figsize=(48,24))
plt.show

"""Problem 2 - Number of Grains outside the 100th day"""

#Creating a Finction to support the Work
def compute_sorori_shinzaemon(day=100):
    #List containing number of Days
    list_n_grains = [(lambda x: x)(x) for x in range(1, day + 1)]

    #The list below shows the total number of rice received per day
    list_total_grains = [2**x-1 for x in range(1, day + 1) ]
    pass
    return list_n_grains, list_total_grains
""""
The function enclosed helps to calculate te amount of Rice a person can get for the number of days he/she has taken the course.
It also allows for inputs from the user of the system.
"""
list_n_grains, list_total_grains = compute_sorori_shinzaemon(day=100)
#Index function to call the total amount
print("days: {}".format(list_n_grains[-1]))
#Index function to call the total amount of grains
print("grains: {}".format(list_total_grains[-1]))

"""Problem 3 - How many People can live for how many days with the rice we get"""

#Creating a Function to support the Work
def compute_sorori_shinzaemon(day=100):
    #List containing number of Days
    list_n_grains2 = [(lambda x: x)(x) for x in range(1, day + 1)]

    #The list below shows the total number of rice received per day
    list_total_grains2 = [2**x-1 for x in range(1, day + 1) ]
    pass
    return list_n_grains2, list_total_grains2
""""
The function enclosed helps to calculate the amount of Rice a person can get for the number of days he/she has taken the course.
It also allows for inputs from the user of the system.
"""
list_n_grains2, list_total_grains2 = compute_sorori_shinzaemon(int(input("Number of Days to Live: ")))
#Index function to call the total amount
print("days: {}".format(list_n_grains2[-1]))
#Index function to call the total amount of grains
print("grains: {}".format(list_total_grains2[-1]))